<a href="https://colab.research.google.com/github/anruki/Rubik_Encription/blob/main/encription_Ana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modelo de cifrado empleando las permutaciones del cubo de Rubik

## Importación de las librerías de python necesarias

In [12]:
import numpy as np
import secrets

La biblioteca `numpy` de python proporciona estructuras como arrays, y funciones para operar con ellos.

- Ejemplo de uso:

In [13]:
# Creación de dos matrices utilizando NumPy
matriz_a = np.array([[1, 2, 3], [4, 5, 6]])
matriz_b = np.array([[7, 8, 9], [10, 11, 12]])

# Multiplicación matricial (producto punto)
producto_punto = np.dot(matriz_a, matriz_b.T)

La biblioteca `secrets` de python permite generar números aleatorios de forma segura (TODO: explicar aquí por qué)

- Ejemplo de uso:

In [ ]:
# Generación de un número aleatorio seguro en el rango especificado
num_aleatorio = secrets.randbelow(100)  # Genera un número aleatorio entre 0 y 99 (inclusive)
print("Número aleatorio:", num_aleatorio)

# Generación de números aleatorios con un número específico de bits
num_aleatorio_bits = secrets.randbits(16)  # Genera un número aleatorio de 16 bits
print("Número aleatorio (16 bits):", num_aleatorio_bits)

Número aleatorio: 29
Número aleatorio (16 bits): 27420


### Transformación binaria

Los ordenadores manejan expresiones en binario y no en el alfabeto. Para simular el proceso de encriptación en un ordenador, crearemos una función que transforme el mensaje a binario.

In [1]:
def transformacion_binaria(mensaje):
    binarios = [format(ord(letra), '08b') for letra in mensaje]
    return binarios


Para representar 26 letras del alfabeto inglés, se necesita un número entero de bits que sea igual o mayor al logaritmo en base 2 de 26 (log₂(26)).

El logaritmo en base 2 de un número N nos dice cuántos bits necesitaríamos para representar N valores distintos. En este caso, el logaritmo en base 2 de 26 es aproximadamente 4.7. Dado que necesitamos un número entero de bits, redondearemos hacia arriba a 5. Por lo tanto, necesitarías al menos 5 bits para representar 26 letras del alfabeto inglés de forma única.

Siempre es recomendable redondear hacia arriba para asegurarnos de tener suficientes bits para representar todos los elementos de manera única. En este caso, redondeamos hacia arriba a 5 bits para representar 26 letras del alfabeto inglés.

Y su función inversa para posteriormente poder decodificar el mensaje:

In [6]:
def transformacion_caracteres(lista_binaria):
    mensaje = ''
    for binario in lista_binaria:
        caracter = chr(int(binario, 2))
        mensaje += caracter
    return mensaje

Probamos con un mensaje de ejemplo:

- Transformación a formato binario:

In [4]:
x = transformacion_binaria('ejemplo')
x = np.array(x)
print(x)

['01100101' '01101010' '01100101' '01101101' '01110000' '01101100'
 '01101111']


- Transformación de formato binario a caracteres:

In [7]:
y = transformacion_caracteres(x)
print(y)

ejemplo


## Transformación del mensaje a numérico

En nuestro caso, para ver fácilmente la operación del proceso de encriptación, vamos a pasar el mensaje en caracteres a un mensaje compuesto por números, cada letra del abecedario es representada por un valor numérico. Por ejemplo:

A: 0
B: 1
C:2

TODO: cifrado César aquí

In [10]:
def caracteres_a_numeros(texto):
    def caracter_a_numero(caracter):
        if not caracter.isalpha():
            return None  # Retornar None si no es un carácter alfabético
        return ord(caracter.lower()) - ord('a')

    # Convertir cada carácter del texto a su equivalente numérico y guardarlos en el array
    numeros = []
    for caracter in texto:
        numero = caracter_a_numero(caracter)
        if numero is not None:
            numeros.append(numero)

    return np.array(numeros)  # Convertir la lista a un array NumPy

Probamos un mensaje de ejemplo y llamamos a la función anterior.

In [11]:
# Cadena de texto de ejemplo
texto = 'abcd'

# Llamar a la función con el texto dado
resultado = caracteres_a_numeros(texto)

print("Números obtenidos:", resultado)

Números obtenidos: [0 1 2 3]


## Creación de la función de encriptación simétrica

El mensaje en binario se le aplica a una matriz que representa las permutaciones del cubo de Rubik. Concretamente es una matriz con 2x3 dimensiones, para representar las 2 caras permutables del cubo y los 3 ejes `[x,y,z]` sobre los que se puede rotar cada cara.

Al tratarse de una estructura cúbica, trabajamos en modulo 4, ya que cada permutación, si se repite el mismo movimiento 4 veces, se vuelve a la posición inicial.

**Generación de la matriz en el cuerpo módulo 4**

Se utiliza:
 - La función `randbelow()` de la biblioteca `secrets` para generar números aleatorios **módulo 4**, es decir de 0 a 3.

- La función `.array()` de la biblioteca `numpy` para obtener una matriz de `3 filas` y `2 columnas`

In [ ]:
import secrets
import numpy as np
# Definir las dimensiones de la matriz
filas = 3
columnas = 2
# Crear la matriz con números aleatorios
matriz_permutaciones = np.array([[secrets.randbelow(4) for _ in range(columnas)] for _ in range(filas)])

La notación de llamada de la función secrets.randbelow(4) y np.array() sigue la convención de utilizar el punto para acceder a los métodos y atributos dentro de un módulo o biblioteca en Python.

**Multiplicación de la matriz por el vector del mensaje**

TODO: si el mensahe es impar, añadir -1

En un cifrado simétrico como este, la matriz (nuestra `llave privada`) tomará valores diferentes cada vez que se encripte un mensaje para una gestión de mensajes más segura.

 Sin embargo, las dimensiones de la matriz de permutaciones siempre son las mismas, y no tienen por qué coincidir con las dimensiones del mensaje a encriptar, es por ello, que se ha de 'trocear' o hacer 'slicing' del mensaje para que independientemente de sus dimensiones, pueda ser multiplicado matricialmente con la matriz de permutaciones.

In [19]:
resultado

array([0, 1, 2, 3])

In [ ]:
cifrado_num = np.dot(matriz_permutaciones, resultado)
# Si el tamaño del mensaje es impar, añado un -1 al final
if resultado.size %2 != 0:
  np.append(resultado,-1)
# hago slice del array mensaje
for i in range(resultado/2):


Pasamos a carácter de nuevo.
TODO: si hay -1 = ''


In [ ]:
def numeros_a_caracteres(numeros):
    def numero_a_caracter(numero):
        if numero < 0 or numero >= 26:
            return None  # Retornar None si el número está fuera del rango válido
        return chr(numero + ord('a'))

    # Convertir cada número en el array a su equivalente alfabético y guardarlos en una lista
    caracteres = []
    for numero in numeros:
        caracter = numero_a_caracter(numero)
        if caracter is not None:
            caracteres.append(caracter)

    # Unir los caracteres en una cadena de texto
    return ''.join(caracteres)
cifrado_char = numeros_a_caracteres(cifrado_num)

In [ ]:
cifrado_char

'bbd'

Para descifrar el mensaje, calculamos la inversa de la matriz transformación:

In [ ]:
import numpy as np
import secrets

# Asegurarse de que numpy y secrets están importados
# La función caracteres_a_numeros ya está definida anteriormente

# Definir las dimensiones de la matriz cuadrada
n = 2

# Crear la matriz de permutaciones cuadrada con números aleatorios
matriz_permutaciones = np.array([[secrets.randbelow(10) for _ in range(n)] for _ in range(n)])
print("Matriz de permutaciones:\n", matriz_permutaciones)

# Asegurar que la matriz tenga inversa (determinante no nulo)
while np.linalg.det(matriz_permutaciones) == 0:
    matriz_permutaciones = np.array([[secrets.randbelow(10) for _ in range(n)] for _ in range(n)])

print("Matriz de permutaciones ajustada (con determinante no nulo):\n", matriz_permutaciones)

# Calcular la inversa de la matriz de permutaciones
matriz_inversa = np.linalg.inv(matriz_permutaciones)
print("Matriz inversa:\n", matriz_inversa)

# Usar la función caracteres_a_numeros para obtener el vector numérico del texto
texto = 'ab'  # Este es el texto de ejemplo
vector_numerico = caracteres_a_numeros(texto)
print("Vector numérico:", vector_numerico)

# Multiplicar la matriz de permutaciones por el vector numérico para obtener el cifrado numérico
cifrado_num = np.dot(matriz_permutaciones, vector_numerico)
print("Cifrado numérico:", cifrado_num)

# Multiplicar la matriz inversa por el cifrado numérico para deshacer el cifrado
resultado_descifrado = np.dot(matriz_inversa, cifrado_num)
print("Resultado descifrado (numérico):", resultado_descifrado)

# Convertir el resultado descifrado a caracteres (opcional)
resultado_descifrado_char = numeros_a_caracteres(np.round(resultado_descifrado).astype(int))
print("Resultado descifrado (texto):", resultado_descifrado_char)


Matriz de permutaciones:
 [[9 8]
 [5 7]]
Matriz de permutaciones ajustada (con determinante no nulo):
 [[9 8]
 [5 7]]
Matriz inversa:
 [[ 0.30434783 -0.34782609]
 [-0.2173913   0.39130435]]
Vector numérico: [0 1]
Cifrado numérico: [8 7]
Resultado descifrado (numérico): [0. 1.]
Resultado descifrado (texto): ab


In [ ]:
import numpy as np

# Definimos el vector v y la matriz_permutaciones
v = np.array(['0110', '0101'])
matriz_permutaciones = np.array([[2, 1], [0, 2], [0, 2]])

# Convertimos el vector a un array de enteros
v_enteros = np.array([int(x, 2) for x in v])

# Realizamos la multiplicación
resultado = np.dot(matriz_permutaciones, v_enteros)

print(resultado)


**División del mensaje para la operación matricial**

In [ ]:
for elemento in x:
  v = np.array([elemento[:4], elemento[4:]])
  np.dot(matriz_permutaciones,v)


## Otros enfoques

In [ ]:
import random

# Definimos los colores posibles en un cubo de Rubik 2x2x2
colores = ['R', 'B', 'G', 'Y', 'W', 'O']

# Generamos una posición aleatoria del cubo de Rubik 2x2x2
posicion_aleatoria = [[[random.choice(colores) for _ in range(2)] for _ in range(2)] for _ in range(2)]

# Mostramos la posición aleatoria generada
print("Posición aleatoria en el cubo de Rubik 2x2x2:")
for capa in posicion_aleatoria:
    for fila in capa:
        print(' '.join(fila))
    print()

In [ ]:
import numpy as np

# Definimos una función para generar una posición aleatoria del cubo de Rubik 2x2x2
def generar_posicion_aleatoria():
    # Definimos los colores posibles como números
    colores = [0, 1, 2, 3, 4, 5]

    # Generamos una matriz 2x2 para cada cara del cubo
    cara_frontal = np.random.choice(colores, size=(2, 2))
    cara_trasera = np.random.choice(colores, size=(2, 2))
    cara_superior = np.random.choice(colores, size=(2, 2))
    cara_inferior = np.random.choice(colores, size=(2, 2))
    cara_izquierda = np.random.choice(colores, size=(2, 2))
    cara_derecha = np.random.choice(colores, size=(2, 2))

    # Devolvemos todas las caras en un arreglo multidimensional
    return [cara_frontal, cara_trasera, cara_superior, cara_inferior, cara_izquierda, cara_derecha]

# Generamos una posición aleatoria
posicion_aleatoria = generar_posicion_aleatoria()

# Mostramos la posición aleatoria generada
print("Posición aleatoria en el cubo de Rubik 2x2x2:")
for cara in posicion_aleatoria:
    print(cara)


In [ ]:
import numpy as np

# Definimos las operaciones de giro para cada cara
def giro_cara_horario(cara):
    return np.rot90(cara, k=-1)

def giro_cara_antihorario(cara):
    return np.rot90(cara, k=1)

# Generamos una posición aleatoria del cubo de Rubik 2x2x2
def generar_posicion_aleatoria():
    colores = [0, 1, 2, 3, 4, 5]
    cara_frontal = np.random.choice(colores, size=(2, 2))
    cara_trasera = np.random.choice(colores, size=(2, 2))
    cara_superior = np.random.choice(colores, size=(2, 2))
    cara_inferior = np.random.choice(colores, size=(2, 2))
    cara_izquierda = np.random.choice(colores, size=(2, 2))
    cara_derecha = np.random.choice(colores, size=(2, 2))
    return [cara_frontal, cara_trasera, cara_superior, cara_inferior, cara_izquierda, cara_derecha]

# Mostramos el estado del cubo de Rubik 2x2x2
def mostrar_estado(posicion):
    print("Estado actual del cubo de Rubik 2x2x2:")
    for cara in posicion:
        print(cara)

# Generamos una posición aleatoria
posicion = generar_posicion_aleatoria()
mostrar_estado(posicion)

# Realizamos un giro en la cara frontal en sentido horario
posicion[0] = giro_cara_horario(posicion[0])

# Mostramos el estado del cubo después del giro
print("\nDespués del giro en la cara frontal en sentido horario:")
mostrar_estado(posicion)


In [ ]:
!pip3 install opencv-python

In [ ]:
!pip uninstall rubik -y

In [ ]:
!pip install rubik-cube

In [ ]:
from rubik.cube import Cube
cubo = Cube("OOOOOOOOOYYYWWWGGGBBBYYYWWWGGGBBBYYYWWWGGGBBBRRRRRRRRR")
print(c)

In [ ]:
import scrambler222

# Generar un scramble aleatorio para un cubo 2x2x2 (WCA)
scramble_wca = scrambler222.get_WCA_scramble("2x2x2")

# Generar un scramble óptimo para un cubo 2x2x2
scramble_optimo = scrambler222.get_optimal_scramble("2x2x2")

print("Scramble aleatorio (WCA) para un cubo 2x2x2:")
print(scramble_wca)

print("\nScramble óptimo para un cubo 2x2x2:")
print(scramble_optimo)
