<a href="https://colab.research.google.com/github/anruki/Rubik_Encription/blob/main/encription.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modelo de cifrado empleando las permutaciones del cubo de Rubik

### Transformación del mensaje a binario

El primer paso será crear una función que transforme el mensaje a binario.

In [79]:
def transformacion_binaria(mensaje):
    binarios = [format(ord(letra), '08b') for letra in mensaje]
    return binarios


Para representar 26 letras del alfabeto inglés, se necesita un número entero de bits que sea igual o mayor al logaritmo en base 2 de 26 (log₂(26)).

El logaritmo en base 2 de un número N nos dice cuántos bits necesitaríamos para representar N valores distintos. En este caso, el logaritmo en base 2 de 26 es aproximadamente 4.7. Dado que necesitamos un número entero de bits, redondearemos hacia arriba a 5. Por lo tanto, necesitarías al menos 5 bits para representar 26 letras del alfabeto inglés de forma única.

Siempre es recomendable redondear hacia arriba para asegurarnos de tener suficientes bits para representar todos los elementos de manera única. En este caso, redondeamos hacia arriba a 5 bits para representar 26 letras del alfabeto inglés.

Y su función inversa para posteriormente poder decodificar el mensaje:

In [81]:
def transformacion_caracteres(lista_binaria):
    mensaje = ''
    for binario in lista_binaria:
        caracter = chr(int(binario, 2))
        mensaje += caracter
    return mensaje

Aquí, bytearray(x, "utf-8") crea un objeto bytearray a partir de la cadena x utilizando la codificación UTF-8. Luego, format(c, '08b') formatea cada byte en la representación binaria de 5 bits ('05b') y se genera una lista de estas representaciones binarias.

Este código generará una lista de representaciones binarias de cada byte en la codificación UTF-8 de la cadena x.

Probamos con un mensaje de ejemplo:

In [96]:
x = transformacion_binaria('ejemplo')
x = np.array(x)
print(x)

['01100101' '01101010' '01100101' '01101101' '01110000' '01101100'
 '01101111']


In [83]:
y = transformacion_caracteres(x)
print(y)

ejemplo


In [9]:
# [bin(ord(c))[2:] for c in 'ejemplo']

['1100101', '1101010', '1100101', '1101101', '1110000', '1101100', '1101111']

## Creación de la función de encriptación simétrica

El mensaje en binario se le aplica a una matriz que representa las permutaciones del cubo de Rubik. Concretamente es una matriz con 2x3 dimensiones, para representar las 2 caras permutables del cubo y los 3 ejes `[x,y,z]` sobre los que se puede rotar cada cara.

Al tratarse de una estructura cúbica, trabajamos en modulo 4, ya que cada permutación, si se repite el mismo movimiento 4 veces, se vuelve a la posición inicial.

**Generación de números aleatorios seguros**

Utilizamos la biblioteca `secrets` de python para generar números aleatorios que no estén en memoria.

In [ ]:
import secrets

# Generar un número aleatorio seguro en el rango especificado
num_aleatorio = secrets.randbelow(100)  # Genera un número aleatorio entre 0 y 99 (inclusive)
print("Número aleatorio:", num_aleatorio)

# También puedes generar números aleatorios con un número específico de bits
num_aleatorio_bits = secrets.randbits(16)  # Genera un número aleatorio de 16 bits
print("Número aleatorio (16 bits):", num_aleatorio_bits)

Número aleatorio: 24
Número aleatorio (16 bits): 44146


**Generación de la matriz en el cuerpo módulo 4**

In [92]:
import secrets
# Definir las dimensiones de la matriz
filas = 3
columnas = 2
# Crear la matriz con números aleatorios
matriz_permutaciones = np.array([[secrets.randbelow(4) for _ in range(columnas)] for _ in range(filas)])

In [93]:
matriz_permutaciones

array([[2, 1],
       [0, 2],
       [0, 2]])

In [89]:
import numpy as np

# Definimos la matriz y el vector como arrays de NumPy
matriz = np.array([[1, 2], [0, 3], [1, 2]])
vector = np.array([1, 2])

# Realizamos la multiplicación
resultado = np.dot(matriz, vector)

print(resultado)


[5 6 5]


In [100]:
x[0]

'01100101'

In [101]:
x[0][:4]

'0110'

In [102]:
x[0][4:]

'0101'

In [104]:
v = np.array([x[0][:4],x[0][4:]])

In [105]:
v

array(['0110', '0101'], dtype='<U4')

In [108]:
import numpy as np

# Definimos el vector v y la matriz_permutaciones
v = np.array(['0110', '0101'])
matriz_permutaciones = np.array([[2, 1], [0, 2], [0, 2]])

# Convertimos el vector a un array de enteros
v_enteros = np.array([int(x, 2) for x in v])

# Realizamos la multiplicación
resultado = np.dot(matriz_permutaciones, v_enteros)

print(resultado)


[17 10 10]


**División del mensaje para la operación matricial**

In [106]:
for elemento in x:
  v = np.array([elemento[:4], elemento[4:]])
  np.dot(matriz_permutaciones,v)


ValueError: data type must provide an itemsize

## Otros enfoques

In [10]:
import random

# Definimos los colores posibles en un cubo de Rubik 2x2x2
colores = ['R', 'B', 'G', 'Y', 'W', 'O']

# Generamos una posición aleatoria del cubo de Rubik 2x2x2
posicion_aleatoria = [[[random.choice(colores) for _ in range(2)] for _ in range(2)] for _ in range(2)]

# Mostramos la posición aleatoria generada
print("Posición aleatoria en el cubo de Rubik 2x2x2:")
for capa in posicion_aleatoria:
    for fila in capa:
        print(' '.join(fila))
    print()

Posición aleatoria en el cubo de Rubik 2x2x2:
Y B
O Y

R W
R O



In [12]:
import numpy as np

# Definimos una función para generar una posición aleatoria del cubo de Rubik 2x2x2
def generar_posicion_aleatoria():
    # Definimos los colores posibles como números
    colores = [0, 1, 2, 3, 4, 5]

    # Generamos una matriz 2x2 para cada cara del cubo
    cara_frontal = np.random.choice(colores, size=(2, 2))
    cara_trasera = np.random.choice(colores, size=(2, 2))
    cara_superior = np.random.choice(colores, size=(2, 2))
    cara_inferior = np.random.choice(colores, size=(2, 2))
    cara_izquierda = np.random.choice(colores, size=(2, 2))
    cara_derecha = np.random.choice(colores, size=(2, 2))

    # Devolvemos todas las caras en un arreglo multidimensional
    return [cara_frontal, cara_trasera, cara_superior, cara_inferior, cara_izquierda, cara_derecha]

# Generamos una posición aleatoria
posicion_aleatoria = generar_posicion_aleatoria()

# Mostramos la posición aleatoria generada
print("Posición aleatoria en el cubo de Rubik 2x2x2:")
for cara in posicion_aleatoria:
    print(cara)


Posición aleatoria en el cubo de Rubik 2x2x2:
[[2 2]
 [5 5]]
[[1 2]
 [3 2]]
[[0 3]
 [4 2]]
[[5 1]
 [0 4]]
[[3 2]
 [2 0]]
[[0 5]
 [3 0]]


In [13]:
import numpy as np

# Definimos las operaciones de giro para cada cara
def giro_cara_horario(cara):
    return np.rot90(cara, k=-1)

def giro_cara_antihorario(cara):
    return np.rot90(cara, k=1)

# Generamos una posición aleatoria del cubo de Rubik 2x2x2
def generar_posicion_aleatoria():
    colores = [0, 1, 2, 3, 4, 5]
    cara_frontal = np.random.choice(colores, size=(2, 2))
    cara_trasera = np.random.choice(colores, size=(2, 2))
    cara_superior = np.random.choice(colores, size=(2, 2))
    cara_inferior = np.random.choice(colores, size=(2, 2))
    cara_izquierda = np.random.choice(colores, size=(2, 2))
    cara_derecha = np.random.choice(colores, size=(2, 2))
    return [cara_frontal, cara_trasera, cara_superior, cara_inferior, cara_izquierda, cara_derecha]

# Mostramos el estado del cubo de Rubik 2x2x2
def mostrar_estado(posicion):
    print("Estado actual del cubo de Rubik 2x2x2:")
    for cara in posicion:
        print(cara)

# Generamos una posición aleatoria
posicion = generar_posicion_aleatoria()
mostrar_estado(posicion)

# Realizamos un giro en la cara frontal en sentido horario
posicion[0] = giro_cara_horario(posicion[0])

# Mostramos el estado del cubo después del giro
print("\nDespués del giro en la cara frontal en sentido horario:")
mostrar_estado(posicion)


Estado actual del cubo de Rubik 2x2x2:
[[1 1]
 [2 4]]
[[3 1]
 [1 2]]
[[4 2]
 [1 1]]
[[3 1]
 [3 2]]
[[5 0]
 [4 3]]
[[0 3]
 [1 1]]

Después del giro en la cara frontal en sentido horario:
Estado actual del cubo de Rubik 2x2x2:
[[2 1]
 [4 1]]
[[3 1]
 [1 2]]
[[4 2]
 [1 1]]
[[3 1]
 [3 2]]
[[5 0]
 [4 3]]
[[0 3]
 [1 1]]


In [50]:
!pip3 install opencv-python

In [32]:
!pip uninstall rubik -y

Found existing installation: Rubik 0.0.1
Uninstalling Rubik-0.0.1:
  Successfully uninstalled Rubik-0.0.1


In [33]:
!pip install rubik-cube

In [53]:
from rubik.cube import Cube
cubo = Cube("OOOOOOOOOYYYWWWGGGBBBYYYWWWGGGBBBYYYWWWGGGBBBRRRRRRRRR")
print(c)

    OOO
    OOO
    OOO
YYY WWW GGG BBB
YYY WWW GGG BBB
YYY WWW GGG BBB
    RRR
    RRR
    RRR


In [52]:
import scrambler222

# Generar un scramble aleatorio para un cubo 2x2x2 (WCA)
scramble_wca = scrambler222.get_WCA_scramble("2x2x2")

# Generar un scramble óptimo para un cubo 2x2x2
scramble_optimo = scrambler222.get_optimal_scramble("2x2x2")

print("Scramble aleatorio (WCA) para un cubo 2x2x2:")
print(scramble_wca)

print("\nScramble óptimo para un cubo 2x2x2:")
print(scramble_optimo)


ModuleNotFoundError: No module named 'scrambler222'